Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
    - db/schema.rb
    - node_modules/**/*.rb
    - bin/*
    - Gemfile
Style/Documentation:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Bundler/OrderedGems:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - config/initializers/devise.rb
inherit_from: .rubocop_todo.yml
