version: '2'
services:
  db:
    image: postgres:9.6.1
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/web
      - node_modules:/web/node_modules
      - bundle:/bundle
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: fresh-mint.*
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
      SENDMAIL_USERNAME:
      SENDMAIL_PASSWORD:
      MAIL_HOST:
volumes:
  postgres:
    driver: local
  node_modules:
    driver: local
  bundle:
    driver: local
