CATEGORY_GROUPS = {
  'Banking': [],
  'Dining': [],
  'Groceries': [],
  'Income': [],
  'Investments': [],
  'None': [],
  'Purchases': [],
  'Recurring Purchases': [],
  'Rent': [],
  'Travel': []
}.stringify_keys!

CATEGORY_GROUP_MAP = {
  'Groceries': 'Groceries',
  'Alcohol & Bars': 'Dining',
  'Coffee Shops': 'Dining',
  'Fast Food': 'Dining',
  'Food & Dining': 'Dining',
  'Restaurants': 'Dining',
  'Air Travel': 'Travel',
  'Auto & Transport': 'Travel',
  'Auto Insurance': 'Travel',
  'Gas & Fuel': 'Travel',
  'Parking': 'Travel',
  'Public Transportation': 'Travel',
  'Rental Car & Taxi': 'Travel',
  'Travel': 'Travel',
  'ATM Fee': 'Purchases',
  'Amusement': 'Purchases',
  'Bank Fee': 'Purchases',
  'Bonus': 'Purchases',
  'Books': 'Purchases',
  'Cash & ATM': 'Purchases',
  'Charity': 'Purchases',
  'Check': 'Purchases',
  'Clothing': 'Purchases',
  'Dentist': 'Purchases',
  'Doctor': 'Purchases',
  'Electronics & Software': 'Purchases',
  'Entertainment': 'Purchases',
  'Federal Tax': 'Purchases',
  'Fees & Charges': 'Purchases',
  'Finance Charge': 'Purchases',
  'Financial Advisor': 'Purchases',
  'Financial': 'Purchases',
  'Furnishings': 'Purchases',
  'Gift': 'Purchases',
  'Hair': 'Purchases',
  'Health Insurance': 'Purchases',
  'Home Improvement': 'Purchases',
  'Home Services': 'Purchases',
  'Home': 'Purchases',
  'Hotel': 'Purchases',
  'Internet': 'Purchases',
  'Late Fee': 'Purchases',
  'Legal': 'Purchases',
  'Misc Expenses': 'Purchases',
  'Movies & DVDs': 'Purchases',
  'Music': 'Purchases',
  'Newspapers & Magazines': 'Purchases',
  'Personal Care': 'Purchases',
  'Pets': 'Purchases',
  'Pharmacy': 'Purchases',
  'Printing': 'Purchases',
  'Service & Parts': 'Purchases',
  'Service Fee': 'Purchases',
  'Shipping': 'Purchases',
  'Shopping': 'Purchases',
  'Sold Items': 'Purchases',
  'Sporting Goods': 'Purchases',
  'Sports': 'Purchases',
  'Stocks': 'Purchases',
  'Vacation': 'Purchases',
  'Gym': 'Recurring Purchases',
  'Mobile Phone': 'Recurring Purchases',
  'Income': 'Income',
  'Interest Income': 'Income',
  'Paycheck': 'Income',
  'Reimbursement': 'Income',
  'Mortgage & Rent': 'Rent',
  'Auto Payment': 'Banking',
  'Business Services': 'Banking',
  'Credit Card Payment': 'Banking',
  'Investments': 'Investments',
  'Investments Transfer': 'Investments',
  'Transfer': 'Banking',
  'State Tax': 'None',
  'Taxes': 'None',
  'Transfer for Cash Spending': 'None',
  'Tuition': 'None',
  'Uncategorized': 'None'
}.stringify_keys!
